# TCL File Generated by Component Editor 13.1
# Thu Nov 14 23:15:56 CST 2013
# DO NOT MODIFY


# 
# Loopback_FIFO "Loopback FIFO" v1.0
# JCJB 2013.11.14.23:15:56
# Component that can be connected to the DMA-330 in the HPS to test DMA channel transfers to/from device peripherals
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module Loopback_FIFO
# 
set_module_property DESCRIPTION "Component that can be connected to the DMA-330 in the HPS to test DMA channel transfers to/from device peripherals"
set_module_property NAME Loopback_FIFO
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR JCJB
set_module_property DISPLAY_NAME "Loopback FIFO"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL flow_control_fifo
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file flow_control_fifo.v VERILOG PATH flow_control_fifo.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL flow_control_fifo
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file flow_control_fifo.v VERILOG PATH flow_control_fifo.v

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL flow_control_fifo
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file flow_control_fifo.v VERILOG PATH flow_control_fifo.v


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER
set_parameter_property DATA_WIDTH DEFAULT_VALUE {32}
set_parameter_property DATA_WIDTH DISPLAY_NAME {Data Slave Width}
set_parameter_property DATA_WIDTH TYPE {INTEGER}
set_parameter_property DATA_WIDTH ALLOWED_RANGES {8 16 32 64 128 256 512 1024}
set_parameter_property DATA_WIDTH DESCRIPTION {Width of the data slave port, this will dictate the width of the internal FIFO}
set_parameter_property DATA_WIDTH UNITS {BITS}
set_parameter_property DATA_WIDTH HDL_PARAMETER true

add_parameter FIFO_DEPTH INTEGER
set_parameter_property FIFO_DEPTH DEFAULT_VALUE {1024}
set_parameter_property FIFO_DEPTH DISPLAY_NAME {Internal FIFO Depth}
set_parameter_property FIFO_DEPTH TYPE {INTEGER}
set_parameter_property FIFO_DEPTH ALLOWED_RANGES {16 32 64 128 256 512 1024 2048 4096 8192}
set_parameter_property FIFO_DEPTH DESCRIPTION {Depth of the internal FIFO in words}
set_parameter_property FIFO_DEPTH DISPLAY_UNITS {words}
set_parameter_property FIFO_DEPTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr readLatency 1
set_interface_property csr readWaitStates 0
set_interface_property csr readWaitTime 0
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_address address Input 3
add_interface_port csr csr_write write Input 1
add_interface_port csr csr_writedata writedata Input 32
add_interface_port csr csr_byteenable byteenable Input 4
add_interface_port csr csr_read read Input 1
add_interface_port csr csr_readdata readdata Output 32
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point data
# 
add_interface data avalon end
set_interface_property data addressUnits WORDS
set_interface_property data associatedClock clock
set_interface_property data associatedReset reset
set_interface_property data bitsPerSymbol 8
set_interface_property data burstOnBurstBoundariesOnly false
set_interface_property data burstcountUnits WORDS
set_interface_property data explicitAddressSpan 0
set_interface_property data holdTime 0
set_interface_property data linewrapBursts false
set_interface_property data maximumPendingReadTransactions 0
set_interface_property data readLatency 0
set_interface_property data readWaitStates 0
set_interface_property data readWaitTime 0
set_interface_property data setupTime 0
set_interface_property data timingUnits Cycles
set_interface_property data writeWaitTime 0
set_interface_property data ENABLED true
set_interface_property data EXPORT_OF ""
set_interface_property data PORT_NAME_MAP ""
set_interface_property data CMSIS_SVD_VARIABLES ""
set_interface_property data SVD_ADDRESS_GROUP ""

add_interface_port data d_address address Input 1
add_interface_port data d_write write Input 1
add_interface_port data d_writedata writedata Input DATA_WIDTH
add_interface_port data d_byteenable byteenable Input DATA_WIDTH/8
add_interface_port data d_read read Input 1
add_interface_port data d_readdata readdata Output DATA_WIDTH
set_interface_assignment data embeddedsw.configuration.isFlash 0
set_interface_assignment data embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment data embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment data embeddedsw.configuration.isPrintableDevice 0


# 
# connection point tx_pri
# 
add_interface tx_pri conduit end
set_interface_property tx_pri associatedClock clock
set_interface_property tx_pri associatedReset ""
set_interface_property tx_pri ENABLED true
set_interface_property tx_pri EXPORT_OF ""
set_interface_property tx_pri PORT_NAME_MAP ""
set_interface_property tx_pri CMSIS_SVD_VARIABLES ""
set_interface_property tx_pri SVD_ADDRESS_GROUP ""

add_interface_port tx_pri tx_single export Output 1
add_interface_port tx_pri tx_burst export Output 1
add_interface_port tx_pri tx_ack export Input 1


# 
# connection point rx_pri
# 
add_interface rx_pri conduit end
set_interface_property rx_pri associatedClock clock
set_interface_property rx_pri associatedReset ""
set_interface_property rx_pri ENABLED true
set_interface_property rx_pri EXPORT_OF ""
set_interface_property rx_pri PORT_NAME_MAP ""
set_interface_property rx_pri CMSIS_SVD_VARIABLES ""
set_interface_property rx_pri SVD_ADDRESS_GROUP ""

add_interface_port rx_pri rx_single export Output 1
add_interface_port rx_pri rx_burst export Output 1
add_interface_port rx_pri rx_ack export Input 1

